"""
Brand monitoring + risk/alerting models.

Split from app/models/trend.py because these represent the "watch this
brand and warn me" layer built on top of the raw topic/mention data --
Topic/Mention/TrendSnapshot/AIInsight would all still make sense in a
product with no brand-monitoring concept at all.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum as SQLEnum,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .mixins import UUIDPKMixin, TimestampMixin
from ..core.database import Base


class RiskLevel(str, enum.Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertType(str, enum.Enum):
    EMERGING_TREND = "EMERGING_TREND"
    SENTIMENT_SHIFT = "SENTIMENT_SHIFT"
    BRAND_RISK = "BRAND_RISK"
    MENTION_SPIKE = "MENTION_SPIKE"
    CROSS_PLATFORM_SPREAD = "CROSS_PLATFORM_SPREAD"


class AlertSeverity(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class Brand(Base, UUIDPKMixin, TimestampMixin):
    """
    A brand/product a user has asked the platform to monitor. Matching
    against incoming posts is keyword-based (see
    app.services.topic_service.match_brand), not ML-based -- deliberately
    simple and auditable per the "why did this post count as a Nike
    mention" question a real user will ask.
    """
    __tablename__ = "brands"

    name: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    aliases: Mapped[list | None] = mapped_column(JSON, nullable=True)   # ["Nike Inc", "Nike Shoes"]
    keywords: Mapped[list | None] = mapped_column(JSON, nullable=True)  # match terms, e.g. ["nike", "air jordan"]
    monitoring_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    risk_assessments: Mapped[list["RiskAssessment"]] = relationship(
        "RiskAssessment", back_populates="brand", cascade="all, delete-orphan"
    )


class RiskAssessment(Base, UUIDPKMixin, TimestampMixin):
    """
    One run of app.services.risk_engine.assess_brand_risk() for a brand.
    `drivers` is the ordered list of {label, points} that summed to
    `risk_score` -- kept so the score is explainable rather than a black
    box (see FEATURE 5 in the product spec).
    """
    __tablename__ = "risk_assessments"

    brand_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("brands.id", ondelete="CASCADE"), nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())

    risk_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)  # 0-100
    risk_level: Mapped[RiskLevel] = mapped_column(SQLEnum(RiskLevel), nullable=False, default=RiskLevel.LOW)
    drivers: Mapped[list | None] = mapped_column(JSON, nullable=True)
    negative_mentions_pct: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    mention_growth_rate: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    platforms_affected: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    complaint_clusters: Mapped[list | None] = mapped_column(JSON, nullable=True)  # ["delivery delays", ...]

    brand: Mapped["Brand"] = relationship("Brand", back_populates="risk_assessments")


class PropagationEvent(Base, UUIDPKMixin):
    """
    A materialized "this topic was first observed on this platform at
    this time, and here is where that ranks in the propagation
    sequence" record, produced by app.services.propagation_engine and
    refreshed each engine run. Stored (rather than computed fresh on
    every request) so the propagation timeline a user saw is stable and
    auditable even as new mentions keep arriving.
    """
    __tablename__ = "propagation_events"
    __table_args__ = (UniqueConstraint("topic_id", "platform", name="uq_propagation_topic_platform"),)

    topic_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("topics.id", ondelete="CASCADE"), nullable=False)
    platform: Mapped[str] = mapped_column(String(32), nullable=False)
    first_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    sequence_order: Mapped[int] = mapped_column(Integer, nullable=False)  # 1 = first platform to see it
    mentions_at_detection: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    growth_since_entry_pct: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    topic: Mapped["Topic"] = relationship("Topic", back_populates="propagation_events")


class Alert(Base, UUIDPKMixin, TimestampMixin):
    """
    A user-facing notification generated by app.services.alert_engine
    when a configured threshold is crossed (trend score, sentiment
    delta, risk score, mention spike, or cross-platform spread).
    """
    __tablename__ = "alerts"

    alert_type: Mapped[AlertType] = mapped_column(SQLEnum(AlertType), nullable=False)
    severity: Mapped[AlertSeverity] = mapped_column(SQLEnum(AlertSeverity), nullable=False, default=AlertSeverity.INFO)
    topic_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("topics.id", ondelete="CASCADE"), nullable=True)
    brand_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("brands.id", ondelete="CASCADE"), nullable=True)
    message: Mapped[str] = mapped_column(String(500), nullable=False)
    drivers: Mapped[dict | list | None] = mapped_column(JSON, nullable=True)
    threshold_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    observed_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    acknowledged: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
