"""add interests to user

Revision ID: 56211dc79502
Revises: df32eef42328
Create Date: 2026-10-05 17:26:38.285853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56211dc79502'
down_revision: Union[str, None] = 'df32eef42328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content_items',
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=16), nullable=False),
    sa.Column('entities_json', sa.JSON(), nullable=True),
    sa.Column('topics_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_category'), 'content_items', ['category'], unique=False)
    op.create_index(op.f('ix_content_items_country_id'), 'content_items', ['country_id'], unique=False)
    op.create_index(op.f('ix_content_items_country_name'), 'content_items', ['country_name'], unique=False)
    op.create_index(op.f('ix_content_items_language'), 'content_items', ['language'], unique=False)
    op.create_index(op.f('ix_content_items_published_at'), 'content_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_content_items_source'), 'content_items', ['source'], unique=False)
    op.create_index(op.f('ix_content_items_source_id'), 'content_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_content_items_source_type'), 'content_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_content_items_url'), 'content_items', ['url'], unique=True)
    op.create_table('events',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latest_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('event_velocity', sa.Float(), nullable=False),
    sa.Column('related_entities', sa.JSON(), nullable=True),
    sa.Column('related_topics', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_snapshots',
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_avg', sa.Float(), nullable=False),
    sa.Column('positive_volume', sa.Integer(), nullable=False),
    sa.Column('neutral_volume', sa.Integer(), nullable=False),
    sa.Column('negative_volume', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mentions', sa.Column('event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'mentions', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('interests', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.drop_column('mentions', 'event_id')
    op.drop_table('sentiment_snapshots')
    op.drop_table('events')
    op.drop_index(op.f('ix_content_items_url'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_source_type'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_source_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_source'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_published_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_language'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_country_name'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_country_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_category'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_table('sources')
    # ### end Alembic commands ###
