import { useParams, Link } from "react-router-dom";
import { AlertTriangle, Brain, GitBranch, Link2, Sparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { LoadingState } from "@/components/shared/LoadingState";
import { ErrorState } from "@/components/shared/ErrorState";
import { EmptyState } from "@/components/shared/EmptyState";
import { SentimentChart } from "@/components/trends/SentimentChart";
import { PropagationTimeline } from "@/components/trends/PropagationTimeline";
import { DemoDataBadge, SentimentBadge } from "@/components/trends/badges";
import { formatEngagement, formatRelativeTime, formatSignedPercent } from "@/lib/formatters";
import {
  useExplanation,
  usePropagation,
  useRelatedTopics,
  useSentimentOverTime,
  useTopPosts,
  useTrendOverview,
} from "@/hooks/queries/useTrends";

/**
 * The trend detail page: overview, the "why is this trending" panel,
 * sentiment over time, cross-platform propagation, related topics, and
 * top conversations. Maps directly onto the five sections spec'd for
 * this page (see Section 15 of the product spec).
 */
export default function TrendDetailPage() {
  const { id } = useParams<{ id: string }>();
  const overview = useTrendOverview(id);
  const sentiment = useSentimentOverTime(id);
  const propagation = usePropagation(id);
  const explanation = useExplanation(id);
  const posts = useTopPosts(id);
  const related = useRelatedTopics(id);

  if (overview.isLoading) return <LoadingState variant="cards" count={3} />;
  if (overview.isError || !overview.data) return <ErrorState title="Trend not found" onRetry={() => overview.refetch()} />;

  const t = overview.data;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-2xl font-semibold text-ink">{t.name}</h1>
        {t.latest && (
          <div className="mt-2 flex flex-wrap items-center gap-4 text-sm">
            <span className={t.latest.growth_rate >= 0 ? "font-semibold text-operational-600" : "font-semibold text-down-600"}>
              {formatSignedPercent(t.latest.growth_rate)} growth
            </span>
            <span className="text-ink-muted">{t.latest.volume} mentions</span>
            <span className="font-mono text-ink-muted">Trend score {t.latest.trend_score.toFixed(0)}/100</span>
            <span className="text-ink-muted">{t.latest.cross_platform_count} platforms</span>
          </div>
        )}
      </div>

      <Card className="border-signal-200 bg-signal-50/40">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-signal-700">
            <Brain className="h-4 w-4" aria-hidden="true" />
            Why is this trending?
            <Sparkles className="ml-auto h-4 w-4 text-signal-400" aria-hidden="true" />
          </CardTitle>
        </CardHeader>
        <CardContent>
          {explanation.isLoading && <LoadingState variant="inline" />}
          {explanation.data && (
            <>
              <p className="text-sm leading-relaxed text-ink">{explanation.data.summary_text}</p>
              <p className="mt-2 text-xs text-ink-faint">
                {explanation.data.generated_by === "llm" ? "Generated by AI, grounded in collected evidence." : "Generated from collected evidence (deterministic explanation engine)."}
              </p>
            </>
          )}
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Sentiment over time</CardTitle>
          </CardHeader>
          <CardContent>
            {sentiment.isLoading ? <LoadingState variant="chart" /> : <SentimentChart points={sentiment.data ?? []} />}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <GitBranch className="h-4 w-4 text-ink-muted" aria-hidden="true" />
              Trend propagation
            </CardTitle>
          </CardHeader>
          <CardContent>
            {propagation.isLoading ? <LoadingState variant="chart" /> : <PropagationTimeline result={propagation.data ?? { established: false, steps: [] }} />}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Top conversations</CardTitle>
        </CardHeader>
        <CardContent>
          {posts.isLoading && <LoadingState variant="table" count={3} />}
          {posts.data && posts.data.length === 0 && <EmptyState title="No posts yet" />}
          {posts.data && posts.data.length > 0 && (
            <ul className="space-y-3">
              {posts.data.map((post) => (
                <li key={post.id} className="rounded-lg border border-border p-3 transition-colors hover:border-border-strong">
                  <div className="flex flex-wrap items-center gap-2 text-xs text-ink-faint">
                    <span className="font-medium capitalize text-ink-muted">{post.platform}</span>
                    {post.author && <span>· {post.author}</span>}
                    <span>· {formatRelativeTime(post.posted_at)}</span>
                    <span>· {formatEngagement(post.engagement_count)} engagement</span>
                    <SentimentBadge label={post.sentiment_label} />
                    {post.is_demo && <DemoDataBadge />}
                    {post.url && (
                      <a href={post.url} target="_blank" rel="noreferrer" className="ml-auto flex items-center gap-1 text-signal-700 hover:underline">
                        <Link2 className="h-3 w-3" aria-hidden="true" />
                        Open
                      </a>
                    )}
                  </div>
                  <p className="mt-1.5 text-sm text-ink">{post.content}</p>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>

      {related.data && related.data.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Related topics</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-2">
            {related.data.map((r) => (
              <Link
                key={r.id}
                to={`/trends/${r.id}`}
                className="rounded-full border border-border px-3 py-1 text-xs font-medium text-ink-muted transition-colors hover:border-signal-300 hover:bg-signal-50 hover:text-signal-700"
              >
                {r.name}
              </Link>
            ))}
          </CardContent>
        </Card>
      )}

      {t.latest && t.latest.negative_pct > 50 && (
        <div className="flex items-center gap-2 rounded-lg border border-down-200 bg-down-50 p-3 text-sm text-down-700">
          <AlertTriangle className="h-4 w-4 shrink-0" aria-hidden="true" />
          Majority-negative sentiment on this topic. If it's tied to a monitored brand, check that brand's risk page.
        </div>
      )}
    </div>
  );
}
