"""GET /alerts, PATCH /alerts/{id}/acknowledge -- alerts are generated by
app.services.alert_engine during the pipeline run, never created directly
via this API."""

from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user
from app.core.database import get_db
from app.models.social import Alert
from app.schemas.social import AlertRead

router = APIRouter()


@router.get("", response_model=list[AlertRead])
async def list_alerts(
    acknowledged: bool | None = None,
    severity: str | None = None,
    limit: int = Query(default=50, le=200),
    db: AsyncSession = Depends(get_db),
    _user=Depends(get_current_user),
):
    stmt = select(Alert).order_by(Alert.created_at.desc()).limit(limit)
    if acknowledged is not None:
        stmt = stmt.where(Alert.acknowledged == acknowledged)
    if severity:
        stmt = stmt.where(Alert.severity == severity)
    res = await db.execute(stmt)
    return res.scalars().all()


@router.patch("/{alert_id}/acknowledge", response_model=AlertRead)
async def acknowledge_alert(alert_id: UUID, db: AsyncSession = Depends(get_db), _user=Depends(get_current_user)):
    res = await db.execute(select(Alert).where(Alert.id == alert_id))
    alert = res.scalar_one_or_none()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found.")
    alert.acknowledged = True
    await db.commit()
    await db.refresh(alert)
    return alert
